import {StickerForm, StickerStyle} from './enum.ts';

import type {StickerListItem, User} from '../types';

const stickersList: StickerListItem[] = [
    {
        id: 1,
        name: 'Sticker 1',
        title: 'Title Company',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.RECTANGLE,
        stickerStyle: StickerStyle.REGULAR,
    },
    {
        id: 2,
        name: 'Sticker 2',
        title: 'Title Company 2',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.RECTANGLE,
        stickerStyle: StickerStyle.REGULAR,
    },
    {
        id: 3,
        name: 'Sticker 3',
        title: 'Title Company 3',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.RECTANGLE,
        stickerStyle: StickerStyle.REGULAR,
    },
    {
        id: 4,
        name: 'Sticker 4',
        title: 'Title Company 4',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.RECTANGLE,
        stickerStyle: StickerStyle.REGULAR,
    },
    {
        id: 5,
        name: 'Sticker 5',
        title: 'Title Company 5',
        highlightedText: 'Super text',
        promo: 'Discount 20%',
        qrCodeLink: 'https://google.com',
        address: 'Address 1117, 7',
        phone: '+1456 36 23',
        titleColor: '#111111',
        highlightedBgColor: '#111111',
        stickerForm: StickerForm.RECTANGLE,
        stickerStyle: StickerStyle.REGULAR,
    },
];

export const DemoUser: User = {
    id: 1,
    name: 'Demo',
    stickersList,
}
